window.ACE_CHAPTERS_DATA = [
  {
    title: 'Tổng quan C++ & cấu trúc chương trình',
    summary: [
      'C/C++ là ngôn ngữ biên dịch. Chương trình C++ bắt đầu chạy từ hàm main().',
      'Biên dịch -> liên kết -> chạy. Thư viện iostream hỗ trợ nhập/xuất với std::cin/std::cout.',
      'Cú pháp dòng lệnh, comment // và /* */; kết thúc câu lệnh bằng dấu chấm phẩy ;',
    ],
    snippets: [
      `#include <iostream>
using namespace std;
int main(){
  cout << "Hello"; 
  return 0;
}`,
    ],
    quiz: [
      {
        type: 'mcq',
        text: 'Hàm nào là điểm bắt đầu chương trình C++?',
        options: ['start()', 'main()', 'init()', 'entry()'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Để in ra màn hình dùng đối tượng nào?',
        options: ['std::in', 'std::cout', 'printf', 'System.out'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'C++ là ngôn ngữ thuộc loại nào?',
        options: ['Thông dịch', 'Biên dịch', 'Script', 'Markup'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Thư viện nào cần include để sử dụng std::cout?',
        options: ['<stdio.h>', '<iostream>', '<string>', '<vector>'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Câu lệnh nào kết thúc chương trình C++?',
        options: ['return 0;', 'exit();', 'break;', 'continue;'],
        answer: 0,
      },
      {
        type: 'mcq',
        text: 'Ký tự nào kết thúc mỗi câu lệnh C++?',
        options: ['.', '?', ';', ','],
        answer: 2,
      },
      {
        type: 'mcq',
        text: 'using namespace std; có tác dụng gì?',
        options: ['Khai báo biến', 'Không cần std::', 'Định nghĩa hàm', 'Kết thúc chương trình'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Comment một dòng trong C++ dùng ký tự?',
        options: ['//', '/*/', ';', '--'],
        answer: 0,
      },
      {
        type: 'mcq',
        text: 'Comment nhiều dòng C++ dùng cú pháp?',
        options: ['// //', '/* */', '<!-- -->', '# #'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Phần mở rộng file mã nguồn C++?',
        options: ['.c', '.cpp', '.java', '.py'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Trình biên dịch C++ phổ biến là?',
        options: ['javac', 'python', 'gcc/g++', 'node'],
        answer: 2,
      },
      {
        type: 'mcq',
        text: 'Quá trình từ code sang file thực thi?',
        options: ['Biên dịch -> Liên kết', 'Thông dịch', 'Chạy trực tiếp', 'Upload'],
        answer: 0,
      },
      {
        type: 'short',
        text: 'Tên hàm bắt buộc có trong mọi chương trình C++?',
        answer: 'main',
      },
      {
        type: 'short',
        text: 'Từ khóa dùng để trả về giá trị từ hàm?',
        answer: 'return',
      },
      {
        type: 'mcq',
        text: '#include có tác dụng?',
        options: [
          'Định nghĩa hàm',
          'Chèn nội dung file khác',
          'Khai báo biến',
          'Kết thúc chương trình',
        ],
        answer: 1,
      },
    ],
  },
  {
    title: 'Biến, kiểu dữ liệu, toán tử, nhập/xuất',
    summary: [
      'Kiểu cơ bản: int, double, char, bool. Hằng số khai báo với const.',
      'Toán tử số học + - * / %, so sánh == != < <= > >=, logic && || !',
      'Nhập xuất căn bản: std::cin >> x; std::cout << x;',
    ],
    snippets: [
      `int a = 5, b = 2;
double c = (double)a / b; // 2.5`,
    ],
    quiz: [
      {
        type: 'mcq',
        text: 'Khai báo hằng số đúng?',
        options: ['const int x=5;', 'int const=5;', 'let x=5;', 'final int x=5;'],
        answer: 0,
      },
      {
        type: 'mcq',
        text: 'Biểu thức 7/2 trong C++ cho kết quả?',
        options: ['3.5', '4', '3', '2'],
        answer: 2,
      },
      {
        type: 'mcq',
        text: 'Kiểu dữ liệu nào lưu số thực?',
        options: ['int', 'double', 'char', 'bool'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Kiểu dữ liệu nào lưu ký tự?',
        options: ['string', 'char', 'int', 'text'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Kiểu bool có thể nhận giá trị nào?',
        options: ['0, 1', 'true, false', 'yes, no', 'T, F'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Toán tử % dùng để?',
        options: ['Chia', 'Lấy phần dư', 'Nhân', 'Cộng'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Toán tử so sánh khác nhau?',
        options: ['=', '!=', '<>', '=/='],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Toán tử logic VÀ trong C++?',
        options: ['&', '&&', 'and', 'AND'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Toán tử logic HOẶC trong C++?',
        options: ['|', '||', 'or', 'OR'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Toán tử logic PHỦ định trong C++?',
        options: ['~', '!', 'not', 'NOT'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Ép kiểu từ int sang double dùng?',
        options: ['(double)x', 'double(x)', 'static_cast<double>(x)', 'Tất cả đều đúng'],
        answer: 3,
      },
      {
        type: 'short',
        text: 'Toán tử nhập dữ liệu từ bàn phím?',
        answer: '>>',
      },
      {
        type: 'short',
        text: 'Toán tử xuất dữ liệu ra màn hình?',
        answer: '<<',
      },
      {
        type: 'mcq',
        text: 'Khai báo biến int đúng?',
        options: ['int a;', 'integer a;', 'Int a;', 'int: a;'],
        answer: 0,
      },
      {
        type: 'mcq',
        text: 'Biểu thức 5 % 3 cho kết quả?',
        options: ['1', '2', '1.67', '5'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Độ ưu tiên toán tử: * và +?',
        options: ['* cao hơn +', '+ cao hơn *', 'Bằng nhau', 'Tùy thuộc'],
        answer: 0,
      },
    ],
  },
  {
    title: 'Cấu trúc rẽ nhánh & vòng lặp',
    summary: [
      'Rẽ nhánh: if/else, else-if. Switch dùng cho so sánh giá trị rời rạc.',
      'Vòng lặp: for, while, do-while. Chú ý điều kiện dừng và lỗi off-by-one.',
    ],
    snippets: [`for(int i=0;i<3;i++){ cout<<i<<" "; } // 0 1 2`],
    quiz: [
      {
        type: 'mcq',
        text: 'Vòng lặp nào luôn chạy thân ít nhất 1 lần?',
        options: ['for', 'while', 'do-while', 'foreach'],
        answer: 2,
      },
      {
        type: 'mcq',
        text: 'Câu lệnh thoát khỏi vòng lặp ngay lập tức?',
        options: ['continue', 'break', 'exit', 'stop'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Cấu trúc if-else được dùng để?',
        options: ['Lặp', 'Rẽ nhánh', 'Khai báo biến', 'Gọi hàm'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'switch-case phù hợp với kiểu dữ liệu nào?',
        options: ['float', 'double', 'int/char', 'string dài'],
        answer: 2,
      },
      {
        type: 'mcq',
        text: 'Câu lệnh continue có tác dụng?',
        options: ['Thoát vòng lặp', 'Bỏ qua lần lặp hiện tại', 'Dừng chương trình', 'Gọi hàm'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Vòng lặp for thích hợp khi?',
        options: [
          'Không biết số lần lặp',
          'Biết trước số lần lặp',
          'Lặp vô hạn',
          'Không bao giờ lặp',
        ],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Vòng lặp while kiểm tra điều kiện?',
        options: ['Sau khi chạy thân', 'Trước khi chạy thân', 'Giữa thân', 'Không kiểm tra'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Cấu trúc else if được dùng khi?',
        options: ['Chỉ có 2 lựa chọn', 'Nhiều điều kiện liên tiếp', 'Vòng lặp', 'Khai báo mảng'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Câu lệnh break trong switch có tác dụng?',
        options: [
          'Tiếp tục case tiếp theo',
          'Thoát khỏi switch',
          'Lặp lại switch',
          'Không có tác dụng',
        ],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Vòng lặp lồng nhau là gì?',
        options: [
          'Vòng lặp bên trong vòng lặp khác',
          'Hai vòng lặp riêng biệt',
          'Vòng lặp sai',
          'Không tồn tại',
        ],
        answer: 0,
      },
      {
        type: 'short',
        text: 'Từ khóa để thoát vòng lặp ngay lập tức?',
        answer: 'break',
      },
      {
        type: 'short',
        text: 'Từ khóa để bỏ qua lần lặp hiện tại?',
        answer: 'continue',
      },
      {
        type: 'mcq',
        text: 'Điều kiện trong while phải có kiểu?',
        options: ['int', 'bool', 'string', 'float'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Vòng lặp do-while khác while ở điểm nào?',
        options: ['Cú pháp khác', 'Kiểm tra điều kiện sau', 'Chạy nhanh hơn', 'Không khác gì'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Lỗi off-by-one thường xảy ra khi?',
        options: ['Dùng sai toán tử', 'Sai điều kiện dừng', 'Quên dấu ;', 'Sai kiểu dữ liệu'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Cú pháp for(int i=0; i<n; i++) có nghĩa?',
        options: ['i từ 0 đến n', 'i từ 0 đến n-1', 'i từ 1 đến n', 'i từ 1 đến n-1'],
        answer: 1,
      },
    ],
  },
  {
    title: 'Hàm & phạm vi',
    summary: [
      'Hàm có kiểu trả về, danh sách tham số. Tham số truyền theo giá trị mặc định.',
      'Có thể dùng tham chiếu (&) để thay đổi đối số bên ngoài.',
    ],
    snippets: [`void increment(int &x){ x++; }`],
    quiz: [
      {
        type: 'mcq',
        text: 'Tham chiếu trong C++ ký hiệu bằng?',
        options: ['*', '&', '->', '%'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Câu lệnh nào khai báo hàm trả về int?',
        options: ['int f();', 'f(): int', 'func int()', 'int: f()'],
        answer: 0,
      },
      {
        type: 'mcq',
        text: 'Hàm main() trả về kiểu dữ liệu gì?',
        options: ['void', 'int', 'char', 'bool'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Truyền tham số theo giá trị có nghĩa là?',
        options: ['Hàm nhận bản sao', 'Hàm nhận địa chỉ', 'Hàm nhận tham chiếu', 'Không truyền gì'],
        answer: 0,
      },
      {
        type: 'mcq',
        text: 'Truyền tham số theo tham chiếu có nghĩa là?',
        options: [
          'Hàm nhận bản sao',
          'Hàm có thể thay đổi biến gốc',
          'Hàm chạy nhanh hơn',
          'Hàm không cần tham số',
        ],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Từ khóa void có nghĩa là?',
        options: ['Hàm trả về số nguyên', 'Hàm không trả về gì', 'Hàm có tham số', 'Hàm riêng tư'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Hàm có thể có bao nhiêu câu lệnh return?',
        options: ['Chỉ 1', 'Tối đa 2', 'Không giới hạn', 'Không có return'],
        answer: 2,
      },
      {
        type: 'mcq',
        text: 'Biến cục bộ được khai báo ở đâu?',
        options: ['Ngoài tất cả hàm', 'Bên trong hàm', 'Trong file header', 'Trước main()'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Biến toàn cục được khai báo ở đâu?',
        options: ['Trong hàm', 'Ngoài tất cả hàm', 'Trong main()', 'Không tồn tại'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Phạm vi (scope) của biến cục bộ là?',
        options: [
          'Toàn chương trình',
          'Chỉ trong hàm khai báo',
          'Chỉ trong file',
          'Trong tất cả file',
        ],
        answer: 1,
      },
      {
        type: 'short',
        text: 'Từ khóa để trả về giá trị từ hàm?',
        answer: 'return',
      },
      {
        type: 'mcq',
        text: 'Hàm có thể gọi hàm khác không?',
        options: ['Không thể', 'Có thể', 'Chỉ trong main()', 'Chỉ hàm void'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Tham số mặc định được viết ở đâu?',
        options: ['Khai báo hàm', 'Định nghĩa hàm', 'Cả hai', 'Không có'],
        answer: 0,
      },
      {
        type: 'mcq',
        text: 'Overloading hàm có nghĩa là?',
        options: ['Hàm quá tải', 'Hàm có cùng tên khác tham số', 'Hàm lồng nhau', 'Hàm đệ quy'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Prototype hàm có tác dụng gì?',
        options: ['Khai báo hàm trước khi định nghĩa', 'Gọi hàm', 'Xóa hàm', 'Sao chép hàm'],
        answer: 0,
      },
      {
        type: 'mcq',
        text: 'Hàm inline có đặc điểm gì?',
        options: ['Chạy chậm', 'Mã được chèn trực tiếp', 'Không có tham số', 'Luôn đệ quy'],
        answer: 1,
      },
    ],
  },
  {
    title: 'Đệ quy',
    summary: [
      'Hàm đệ quy gọi lại chính nó; cần điều kiện dừng để tránh lặp vô hạn.',
      'Ví dụ: giai thừa, Fibonacci.',
    ],
    snippets: [`int fact(int n){ return (n<=1)?1:n*fact(n-1); }`],
    quiz: [
      {
        type: 'mcq',
        text: 'Điều gì cần có trong hàm đệ quy?',
        options: ['goto', 'biến toàn cục', 'điều kiện dừng', 'mảng tĩnh'],
        answer: 2,
      },
      {
        type: 'mcq',
        text: 'fact(3) với fact(n) = n*fact(n-1), fact(1)=1 là?',
        options: ['3', '5', '6', '9'],
        answer: 2,
      },
      {
        type: 'mcq',
        text: 'Đệ quy là gì?',
        options: [
          'Hàm gọi hàm khác',
          'Hàm gọi chính nó',
          'Hàm có nhiều tham số',
          'Hàm không có return',
        ],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Điều kiện dừng trong đệ quy có tác dụng gì?',
        options: ['Làm chương trình chậm', 'Ngăn lặp vô hạn', 'Tăng tốc độ', 'Không có tác dụng'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Fibonacci(0) = 0, Fibonacci(1) = 1, Fibonacci(2) = ?',
        options: ['0', '1', '2', '3'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Đệ quy có nhược điểm gì?',
        options: ['Khó hiểu', 'Tốn bộ nhớ stack', 'Chậm hơn vòng lặp', 'Tất cả đều đúng'],
        answer: 3,
      },
      {
        type: 'mcq',
        text: 'Base case trong đệ quy là gì?',
        options: [
          'Trường hợp cơ bản không đệ quy',
          'Trường hợp phức tạp nhất',
          'Trường hợp lỗi',
          'Không tồn tại',
        ],
        answer: 0,
      },
      {
        type: 'mcq',
        text: 'Stack overflow xảy ra khi nào?',
        options: [
          'Đệ quy không có điều kiện dừng',
          'Đệ quy quá nhanh',
          'Đệ quy quá chậm',
          'Không bao giờ',
        ],
        answer: 0,
      },
      {
        type: 'mcq',
        text: 'Tính giai thừa 0! = ?',
        options: ['0', '1', 'Không xác định', 'Lỗi'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Đệ quy tuyến tính là gì?',
        options: [
          'Hàm gọi chính nó 1 lần',
          'Hàm gọi chính nó 2 lần',
          'Hàm không đệ quy',
          'Hàm lặp vô hạn',
        ],
        answer: 0,
      },
      {
        type: 'short',
        text: 'Bài toán kinh điển dùng đệ quy tính giai thừa?',
        answer: 'factorial',
      },
      {
        type: 'mcq',
        text: 'Đệ quy nhị phân là gì?',
        options: [
          'Hàm gọi chính nó 1 lần',
          'Hàm gọi chính nó 2 lần',
          'Hàm có 2 tham số',
          'Hàm trả về bool',
        ],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Tháp Hà Nội là bài toán gì?',
        options: ['Vòng lặp', 'Đệ quy', 'Mảng', 'Con trỏ'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Đệ quy đuôi (tail recursion) là gì?',
        options: ['Đệ quy ở cuối hàm', 'Đệ quy ở đầu hàm', 'Đệ quy ở giữa', 'Không tồn tại'],
        answer: 0,
      },
      {
        type: 'mcq',
        text: 'Có thể thay thế đệ quy bằng gì?',
        options: ['Không thể thay thế', 'Vòng lặp + stack', 'Chỉ vòng lặp', 'Chỉ mảng'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Khi nào nên dùng đệ quy?',
        options: ['Luôn luôn', 'Không bao giờ', 'Khi bài toán có cấu trúc đệ quy', 'Khi muốn chậm'],
        answer: 2,
      },
    ],
  },
  {
    title: 'Mảng một chiều',
    summary: [
      'Mảng có kích thước cố định, chỉ số từ 0..n-1. Truy cập ngoài phạm vi gây lỗi.',
      'Duyệt mảng bằng for; nhớ khởi tạo giá trị.',
    ],
    snippets: [`int a[3]={2,4,6}; cout<<a[1]; // 4`],
    quiz: [
      {
        type: 'mcq',
        text: 'Chỉ số phần tử đầu tiên của mảng?',
        options: ['0', '1', '-1', 'tùy'],
        answer: 0,
      },
      {
        type: 'mcq',
        text: 'Kích thước mảng int a[10] là?',
        options: ['9', '10', '11', 'phụ thuộc'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Khai báo mảng 5 phần tử đúng?',
        options: ['int a(5);', 'int a[5];', 'array<int> a(5);', 'int [5] a;'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Truy cập phần tử cuối của mảng a[n]?',
        options: ['a[n]', 'a[n-1]', 'a[n+1]', 'a.last()'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Khởi tạo mảng {1,2,3} đúng?',
        options: [
          'int a[] = {1,2,3};',
          'int a = {1,2,3};',
          'int a[3] = 1,2,3;',
          'array a = {1,2,3};',
        ],
        answer: 0,
      },
      {
        type: 'mcq',
        text: 'Duyệt mảng a[n] bằng vòng lặp nào?',
        options: [
          'for(i=1; i<=n; i++)',
          'for(i=0; i<n; i++)',
          'for(i=0; i<=n; i++)',
          'while(true)',
        ],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Lỗi gì khi truy cập a[10] với mảng a[5]?',
        options: ['Compile error', 'Runtime error', 'Out of bounds', 'Tất cả đều đúng'],
        answer: 2,
      },
      {
        type: 'mcq',
        text: 'Mảng có thể thay đổi kích thước không?',
        options: [
          'Có, bất kỳ lúc nào',
          'Không, kích thước cố định',
          'Chỉ khi khai báo',
          'Tùy thuộc kiểu dữ liệu',
        ],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Tìm phần tử lớn nhất mảng cần?',
        options: ['Duyệt 1 lần', 'Duyệt 2 lần', 'Sắp xếp trước', 'Không thể tìm'],
        answer: 0,
      },
      {
        type: 'mcq',
        text: 'Sắp xếp mảng bubble sort có độ phức tạp?',
        options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(1)'],
        answer: 2,
      },
      {
        type: 'short',
        text: 'Thuật toán tìm kiếm tuyến tính trong mảng?',
        answer: 'linear search',
      },
      {
        type: 'mcq',
        text: 'Binary search yêu cầu mảng?',
        options: ['Bất kỳ', 'Đã sắp xếp', 'Có số lẻ phần tử', 'Toàn số dương'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Chèn phần tử vào đầu mảng cần?',
        options: [
          'Dịch chuyển các phần tử',
          'Không cần làm gì',
          'Xóa phần tử cuối',
          'Tạo mảng mới',
        ],
        answer: 0,
      },
      {
        type: 'mcq',
        text: 'Mảng được lưu trữ trong bộ nhớ như thế nào?',
        options: ['Ngẫu nhiên', 'Liên tiếp', 'Theo giá trị', 'Theo thứ tự abc'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Khởi tạo mảng không gán giá trị sẽ?',
        options: ['Toàn số 0', 'Giá trị rác', 'Lỗi compile', 'Toàn số 1'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Truyền mảng vào hàm C++ truyền?',
        options: ['Giá trị', 'Tham chiếu', 'Con trỏ đến phần tử đầu', 'Bản sao'],
        answer: 2,
      },
    ],
  },
  {
    title: 'Mảng hai chiều & ma trận',
    summary: [
      'Khai báo: int a[R][C]; Duyệt hai vòng lặp lồng nhau.',
      'Ứng dụng: tính tổng hàng/cột, đường chéo.',
    ],
    snippets: [`int s=0; for(int i=0;i<n;i++) for(int j=0;j<m;j++) s+=a[i][j];`],
    quiz: [
      {
        type: 'mcq',
        text: 'Khai báo ma trận 2x3 đúng?',
        options: ['int a[2,3];', 'int a(2)(3);', 'int a[2][3];', 'matrix<int,2,3> a;'],
        answer: 2,
      },
      {
        type: 'mcq',
        text: 'Truy cập phần tử hàng 1, cột 2 của ma trận a?',
        options: ['a[1,2]', 'a[1][2]', 'a(1,2)', 'a.get(1,2)'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Duyệt ma trận m×n cần mấy vòng lặp?',
        options: ['1', '2', '3', 'm+n'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Ma trận 3×4 có bao nhiêu phần tử?',
        options: ['7', '12', '16', '9'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Khởi tạo ma trận 2×2 đúng?',
        options: [
          'int a[2][2] = {{1,2},{3,4}};',
          'int a[2][2] = {1,2,3,4};',
          'Cả hai đều đúng',
          'Cả hai đều sai',
        ],
        answer: 2,
      },
      {
        type: 'mcq',
        text: 'Tính tổng đường chéo chính ma trận vuông n×n?',
        options: [
          'for(i=0;i<n;i++) sum+=a[i][i]',
          'for(i=0;i<n;i++) sum+=a[i][n-i]',
          'for(i=0;i<n;i++) sum+=a[i][0]',
          'for(i=0;i<n;i++) sum+=a[0][i]',
        ],
        answer: 0,
      },
      {
        type: 'mcq',
        text: 'Ma trận chuyển vị có kích thước nào từ ma trận 3×5?',
        options: ['3×5', '5×3', '3×3', '5×5'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Tìm phần tử lớn nhất ma trận m×n cần?',
        options: ['1 vòng lặp', '2 vòng lặp lồng nhau', '3 vòng lặp', 'Không thể'],
        answer: 1,
      },
      {
        type: 'short',
        text: 'Ký tự ngăn cách khi khởi tạo ma trận?',
        answer: ',',
      },
      {
        type: 'mcq',
        text: 'Ma trận đơn vị có đặc điểm gì?',
        options: ['Tất cả phần tử = 1', 'Đường chéo chính = 1, còn lại = 0', 'Đối xứng', 'Vuông'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Nhân hai ma trận A(m×n) và B(p×q) yêu cầu?',
        options: ['m=p', 'n=p', 'm=q', 'n=q'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Ma trận được lưu trong bộ nhớ theo thứ tự?',
        options: ['Ngẫu nhiên', 'Theo hàng', 'Theo cột', 'Tùy compiler'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Tính tổng từng hàng ma trận cần?',
        options: ['1 vòng for', '2 vòng for lồng nhau', '3 vòng for', 'while'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Ma trận tam giác trên có đặc điểm?',
        options: [
          'a[i][j]=0 khi i>j',
          'a[i][j]=0 khi i<j',
          'a[i][j]=0 khi i=j',
          'Không có đặc điểm',
        ],
        answer: 0,
      },
      {
        type: 'mcq',
        text: 'Truyền ma trận vào hàm C++ như thế nào?',
        options: ['Truyền giá trị', 'Truyền con trỏ', 'Truyền tham chiếu', 'Cả B và C'],
        answer: 3,
      },
    ],
  },
  {
    title: 'Chuỗi ký tự (C-style)',
    summary: [
      "Chuỗi C kết thúc bằng ký tự '\\0'. Thao tác với <cstring>: strlen, strcpy, strcmp...",
      'Cẩn thận tràn bộ đệm khi sao chép chuỗi.',
    ],
    snippets: [`char s[10]="abc"; cout<<strlen(s); // 3`],
    quiz: [
      {
        type: 'mcq',
        text: 'Chuỗi C kết thúc bằng?',
        options: ['\\n', '\\0', 'EOF', 'space'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Hàm so sánh 2 chuỗi?',
        options: ['strcat', 'strcmp', 'strcpy', 'strlen'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Hàm đo độ dài chuỗi?',
        options: ['length()', 'strlen()', 'size()', 'count()'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Hàm sao chép chuỗi?',
        options: ['strcpy()', 'strcat()', 'strcmp()', 'strchr()'],
        answer: 0,
      },
      {
        type: 'mcq',
        text: 'Hàm nối chuỗi?',
        options: ['strcpy()', 'strcat()', 'strcmp()', 'strlen()'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Khai báo chuỗi "hello" đúng?',
        options: [
          'char s[5] = "hello";',
          'char s[6] = "hello";',
          'char s[] = "hello";',
          'B và C đều đúng',
        ],
        answer: 3,
      },
      {
        type: 'mcq',
        text: 'strcmp("abc", "abc") trả về?',
        options: ['0', '1', '-1', '3'],
        answer: 0,
      },
      {
        type: 'mcq',
        text: 'strlen("hello") trả về?',
        options: ['4', '5', '6', 'Lỗi'],
        answer: 1,
      },
      {
        type: 'short',
        text: 'Ký tự kết thúc chuỗi C?',
        answer: '\\0',
      },
      {
        type: 'mcq',
        text: 'Hàm tìm ký tự trong chuỗi?',
        options: ['strchr()', 'strstr()', 'strcmp()', 'strcpy()'],
        answer: 0,
      },
      {
        type: 'mcq',
        text: 'Hàm tìm chuỗi con?',
        options: ['strchr()', 'strstr()', 'strcmp()', 'strcat()'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Chuỗi rỗng có độ dài?',
        options: ['0', '1', '-1', 'Không xác định'],
        answer: 0,
      },
      {
        type: 'mcq',
        text: 'char s[10] = "hi"; thì s[2] = ?',
        options: ["'i'", "'\\0'", 'Lỗi', 'Rác'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Đọc chuỗi có khoảng trống dùng?',
        options: ['cin >>', 'getline()', 'scanf()', 'B và C đều đúng'],
        answer: 3,
      },
      {
        type: 'mcq',
        text: 'Buffer overflow xảy ra khi?',
        options: ['Chuỗi quá ngắn', 'Chuỗi vượt kích thước mảng', 'Chuỗi rỗng', 'Không bao giờ'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Chuyển chuỗi sang số dùng?',
        options: ['atoi()', 'stoi()', 'Cả hai', 'Không thể'],
        answer: 2,
      },
    ],
  },
  {
    title: 'Con trỏ & cấp phát động',
    summary: [
      'Con trỏ lưu địa chỉ biến. Toán tử &: lấy địa chỉ; *: truy cập giá trị tại địa chỉ.',
      'Cấp phát động: new/delete.',
    ],
    snippets: [`int x=10; int *p=&x; *p=20; // x=20`],
    quiz: [
      {
        type: 'mcq',
        text: 'Toán tử lấy địa chỉ biến?',
        options: ['*', '&', '->', '%'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Giải phóng bộ nhớ cấp phát bằng new?',
        options: ['free', 'delete', 'dispose', 'release'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Toán tử truy cập giá trị qua con trỏ?',
        options: ['&', '*', '->', '[]'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Khai báo con trỏ int đúng?',
        options: ['int p*;', 'int *p;', '*int p;', 'pointer<int> p;'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Con trỏ NULL trỏ đến đâu?',
        options: ['Địa chỉ 0', 'Không trỏ đến đâu', 'Vùng nhớ đặc biệt', 'A và B đúng'],
        answer: 3,
      },
      {
        type: 'mcq',
        text: 'Cấp phát mảng động 10 phần tử int?',
        options: ['new int[10]', 'malloc(10)', 'int[10] new', 'alloc int[10]'],
        answer: 0,
      },
      {
        type: 'mcq',
        text: 'Giải phóng mảng động dùng?',
        options: ['delete p', 'delete[] p', 'free(p)', 'B và C đúng'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Con trỏ p trỏ đến int x, *p = 5 có nghĩa?',
        options: ['p = 5', 'x = 5', 'Địa chỉ x = 5', 'Lỗi'],
        answer: 1,
      },
      {
        type: 'short',
        text: 'Từ khóa cấp phát bộ nhớ động trong C++?',
        answer: 'new',
      },
      {
        type: 'mcq',
        text: 'Con trỏ void* có thể?',
        options: ['Trỏ bất kỳ kiểu nào', 'Chỉ trỏ int', 'Chỉ trỏ char', 'Không tồn tại'],
        answer: 0,
      },
      {
        type: 'mcq',
        text: 'Con trỏ hằng (const pointer) có đặc điểm?',
        options: [
          'Không thể thay đổi địa chỉ',
          'Không thể thay đổi giá trị',
          'Cả hai',
          'Không có đặc biệt',
        ],
        answer: 0,
      },
      {
        type: 'mcq',
        text: 'Pointer arithmetic: p++ có nghĩa?',
        options: [
          'Tăng địa chỉ 1 byte',
          'Tăng địa chỉ 1 đơn vị kiểu dữ liệu',
          'Tăng giá trị tại p',
          'Lỗi',
        ],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Con trỏ đến con trỏ khai báo như nào?',
        options: ['int *p;', 'int **p;', 'int ptr*p;', 'pointer int p;'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Memory leak xảy ra khi?',
        options: [
          'Dùng new nhưng không delete',
          'Dùng delete nhiều lần',
          'Dùng con trỏ NULL',
          'Không có memory leak',
        ],
        answer: 0,
      },
      {
        type: 'mcq',
        text: 'Dangling pointer là gì?',
        options: [
          'Con trỏ NULL',
          'Con trỏ trỏ vùng nhớ đã giải phóng',
          'Con trỏ hằng',
          'Con trỏ void',
        ],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'Con trỏ hàm dùng để?',
        options: ['Trỏ đến hàm', 'Tham số hàm', 'Callback', 'Tất cả đều đúng'],
        answer: 3,
      },
    ],
  },
  {
    title: 'struct (kiểu dữ liệu cấu trúc)',
    summary: [
      'struct gom nhóm nhiều trường. Truy cập bằng dấu chấm. Có thể truyền struct vào hàm.',
      'Có thể tạo mảng struct để quản lý danh sách.',
    ],
    snippets: [
      `struct SV{ string name; int age; };
SV a={"An",19}; cout<<a.name;`,
    ],
    quiz: [
      {
        type: 'mcq',
        text: 'Truy cập trường của struct dùng?',
        options: ['.', '->', '::', '#'],
        answer: 0,
      },
      {
        type: 'mcq',
        text: 'Từ khóa khai báo struct?',
        options: ['class', 'struct', 'record', 'type'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'struct có thể chứa?',
        options: ['Chỉ biến', 'Chỉ hàm', 'Cả biến và hàm', 'Chỉ số'],
        answer: 2,
      },
      {
        type: 'mcq',
        text: 'Khai báo struct Student đúng?',
        options: [
          'struct Student { int id; };',
          'Student struct { int id; };',
          'struct { int id; } Student;',
          'A và C đúng',
        ],
        answer: 3,
      },
      {
        type: 'mcq',
        text: 'Khởi tạo struct Point{int x,y;} đúng?',
        options: ['Point p = {1,2};', 'Point p(1,2);', 'Point p; p.x=1; p.y=2;', 'Tất cả đều đúng'],
        answer: 3,
      },
      {
        type: 'mcq',
        text: 'Con trỏ struct truy cập trường dùng?',
        options: ['.', '->', 'Cả hai', '::'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'struct trong C++ khác class ở điểm nào?',
        options: [
          'Không khác gì',
          'struct public mặc định',
          'class private mặc định',
          'B và C đúng',
        ],
        answer: 3,
      },
      {
        type: 'mcq',
        text: 'Truyền struct vào hàm có thể?',
        options: ['Theo giá trị', 'Theo tham chiếu', 'Theo con trỏ', 'Tất cả đều được'],
        answer: 3,
      },
      {
        type: 'short',
        text: 'Toán tử truy cập trường qua con trỏ struct?',
        answer: '->',
      },
      {
        type: 'mcq',
        text: 'Mảng struct khai báo như nào?',
        options: ['Student arr[10];', 'struct Student arr[10];', 'Student[10] arr;', 'A và B đúng'],
        answer: 3,
      },
      {
        type: 'mcq',
        text: 'struct lồng nhau có được không?',
        options: ['Không', 'Có', 'Chỉ 1 cấp', 'Tùy compiler'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'struct có constructor không?',
        options: ['Không', 'Có', 'Tùy version C++', 'Chỉ C++ 11+'],
        answer: 1,
      },
      {
        type: 'mcq',
        text: 'So sánh 2 struct bằng == được không?',
        options: ['Được', 'Không được', 'Chỉ primitive type', 'Phải overload'],
        answer: 3,
      },
      {
        type: 'mcq',
        text: 'struct có thể kế thừa không?',
        options: ['Không', 'Có', 'Chỉ public', 'Giống class'],
        answer: 3,
      },
      {
        type: 'mcq',
        text: 'Kích thước struct bằng?',
        options: [
          'Tổng kích thước các trường',
          'Lớn hơn tổng (padding)',
          'Tùy thuộc',
          'B và C đúng',
        ],
        answer: 3,
      },
      {
        type: 'mcq',
        text: 'struct thích hợp cho?',
        options: [
          'Nhóm dữ liệu liên quan',
          'POD (Plain Old Data)',
          'Truyền dữ liệu',
          'Tất cả đều đúng',
        ],
        answer: 3,
      },
    ],
  },
]
